//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Mvc;

namespace FIT5032_HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int BookingNumber { get; set; }
        public int HotelId { get; set; }
        public string UserId { get; set; }
        public List<SelectListItem> List { get; set; }

        public virtual Hotel Hotel { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
