//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public int RatingClass { get; set; }
        public string UsersId { get; set; }
        public int HotelId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
