// <auto-generated />
namespace FIT5032_MyCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202107180947 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202107180947));
        
        string IMigrationMetadata.Id
        {
            get { return "202107180148114_202107180947"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
